# Generated by Django 4.1.2 on 2022-11-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200)),
                ('prijmeni', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=15)),
                ('ulice_cp', models.CharField(max_length=200)),
                ('mesto', models.CharField(max_length=100)),
                ('psc', models.CharField(max_length=9)),
                ('stat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypPojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_pojisteni', models.CharField(max_length=100)),
                ('hodnota_pojisteni', models.CharField(max_length=10)),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojistenci.pojistenec')),
            ],
        ),
    ]
