# Generated by Django 4.1.2 on 2022-11-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typpojisteni',
            name='pojistenec',
        ),
        migrations.AddField(
            model_name='pojistenec',
            name='typ_pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.typpojisteni'),
        ),
    ]
