# Generated by Django 4.1.2 on 2022-11-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0002_remove_typpojisteni_pojistenec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typpojisteni',
            name='hodnota_pojisteni',
        ),
        migrations.CreateModel(
            name='SeznamPojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet_pojisteni', models.CharField(max_length=80)),
                ('hodnota_pojisteni', models.CharField(max_length=10)),
                ('plati_od', models.CharField(max_length=10)),
                ('plati_do', models.CharField(max_length=10)),
                ('typ_pojisteni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.typpojisteni')),
            ],
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='typ_pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.seznampojisteni'),
        ),
    ]
