# Generated by Django 4.1.2 on 2022-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0003_remove_typpojisteni_hodnota_pojisteni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenec',
            name='typ_pojisteni',
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='pojistenec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.pojistenec'),
        ),
    ]
