# Generated by Django 4.1.2 on 2022-11-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0004_remove_pojistenec_typ_pojisteni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojistenec',
            options={'verbose_name': 'Pojištěnec', 'verbose_name_plural': 'Pojištěnci'},
        ),
        migrations.AlterModelOptions(
            name='seznampojisteni',
            options={'verbose_name': 'Seznam pojištění', 'verbose_name_plural': 'Seznam pojištění'},
        ),
        migrations.AlterModelOptions(
            name='typpojisteni',
            options={'verbose_name': 'Typ pojištění', 'verbose_name_plural': 'Typy pojištění'},
        ),
    ]
