# Generated by Django 4.1.2 on 2022-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0006_uzivatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='telefon',
            field=models.FloatField(max_length=15),
        ),
    ]
