# Generated by Django 4.1.2 on 2022-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0007_alter_pojistenec_email_alter_pojistenec_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='telefon',
            field=models.CharField(max_length=15),
        ),
    ]
