# Generated by Django 4.1.2 on 2022-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0008_alter_pojistenec_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Stát',
                'verbose_name_plural': 'Státy',
            },
        ),
    ]
