# Generated by Django 4.1.2 on 2022-11-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0010_alter_pojistenec_jmeno_alter_pojistenec_mesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojistenec',
            name='stat',
        ),
    ]
