# Generated by Django 4.1.2 on 2022-11-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0011_remove_pojistenec_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenec',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.stat', verbose_name='Stát'),
        ),
    ]
