# Generated by Django 4.1.2 on 2022-11-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0015_alter_seznampojisteni_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seznampojisteni',
            options={'verbose_name': 'Seznam pojištění', 'verbose_name_plural': 'Seznam pojištění'},
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='hodnota_pojisteni',
            field=models.CharField(max_length=10, null=True, verbose_name='Hodnota pojištění'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='plati_do',
            field=models.CharField(max_length=10, null=True, verbose_name='Platí do'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='plati_od',
            field=models.CharField(max_length=10, null=True, verbose_name='Platí od'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='pojistenec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.pojistenec', verbose_name='Pojištěnec'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='poznamka',
            field=models.TextField(null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='predmet_pojisteni',
            field=models.CharField(max_length=80, null=True, verbose_name='Předmět pojištění'),
        ),
        migrations.AddField(
            model_name='seznampojisteni',
            name='typ_pojisteni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojistenci.typpojisteni', verbose_name='Druh pojištění'),
        ),
    ]
