# Generated by Django 4.1.2 on 2022-11-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0017_alter_seznampojisteni_poznamka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzivatel',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AlterField(
            model_name='seznampojisteni',
            name='pojistenec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pojistenci.pojistenec', verbose_name='Pojištěnec'),
        ),
    ]
